### ISSUE TITLE
Readme: usage is vague

### ISSUE THREAD

**Issue by joyously** [WPTT/control-color-alpha#1]
For the Readme.md file, the Usage section is all about getting the code into your project.
But it doesn't say anything about the actual usage of the control. 
What is the format of the value?
Why does the default value have no alpha?
What function should be used to sanitize or is that already handled? How about escaping?
Is this using the new 8 digit hex code or rgba or hsla? Can you choose?

**Comment by aristath** [comment]
Good points, I'll need to rewrite the readme file a bit and add some clarifications.

> What is the format of the value?

hex (`#000000`) or rgba(`rgba(0,0,0,1)`)

> Why does the default value have no alpha?

You can use any hex or rgba value as default.

> What function should be used to sanitize or is that already handled?

It's a control, so it doesn't handle sanitizing. These should be handled by theme-authors. But I do have [a function than handles sanitization](https://github.com/kirki-framework/control-color/blob/758636198eff9ecfac11b364dddb5336ba17334c/src/Field/Color.php#L118-L136) for colors, we can include it in a helper class in this package for convenience. But again, this is outside the scope of a control. It would be appropriate to just put something in the readme file for authors to use as they see fit.

> How about escaping?

It's a control all it does is save a value. How authors use that value is up to them. Escaping would depend on the context and where/how the value is being used.

> Is this using the new 8 digit hex code or rgba or hsla? Can you choose?

The new 8-digit hex codes (I call them octets, I don't know if they have an official name) is not widely supported by browsers so that was out of the question at this time. Out of all the formats for colors `hex` and `rgba` are the most supported ones, so these are the ones the control uses.
In this first release we didn't want to add many options like saving formats etc. We were talking about adding an extra argument to allow saving any format desired - including an array with various properties, something like this:
```php
[
    'rgba'       => 'rgba(255,255,255,1)',
    'hex'        => '#ffffff',
    'red'        => 255,
    'green'      => 255,
    'blue'       => 255,
    'hue'        => 100,
    'saturation' => 0,
    'lightness'  => 100,
    'luminosity' => 1,
]
```
However for v1.0 we want to keep this simple and release a package that theme-authors can use. Once it's out we can expand on the logic and add more cases. In its current form it will cover the majority of use-cases with the hex & rgba formats.

**Comment by joyously** [comment]
Thanks for the answers, but they should be in the readme under Usage. I don't think it's a bad thing to remind authors how best to sanitize or escape the data that the control provides.
WP has `sanitize_hex_color` but nothing really to handle rgba. But if it could be either, how does one know which to use? Would it need a hybrid function that allows either? (or maybe I'm thinking validation, which could go in the control class)

**Comment by aristath** [comment]
They will be in the readme, it was late and I couldn't push a commit at that time.
We should probably decide what to do with #2 first since I'll have to rewrite the readme for that anyway.

P.S. Thank you for both issues you created, that's why no stable release was tagged yet - I'd like to fix any issues that come up first. #2 is a big one...

**Comment by aristath** [comment]
Changes applied to readme file

**Comment by joyously** [comment]
Awesome!
